### ISSUE TITLE
ImportError: No module named _thread

### ISSUE THREAD

**Issue by epicserve** [thauber/django-schedule#42]
I get the following traceback when I try to run `django-admin.py syncdb` for the first time. I'm using the `project_sample` provided.

```
$ django-admin.py runserver 
Validating models...

Unhandled exception in thread started by <bound method Command.inner_run of <django.core.management.commands.runserver.Command object at 0x10d798550>>
Traceback (most recent call last):
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 88, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/core/management/validation.py", line 35, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name)
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/schedule/models/__init__.py", line 1, in <module>
    from schedule.models.calendars import *
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/schedule/models/calendars.py", line 11, in <module>
    from dateutil import rrule
  File "/Users/oconnor/.virtualenvs/django-schedule/lib/python2.7/site-packages/dateutil/rrule.py", line 13, in <module>
    import _thread
ImportError: No module named _thread
```

I have the following packages installed in a virtualenv:

``` bash
$ pip freeze
BeautifulSoup==3.2.0
Django==1.3.1
django-appconf==0.4.1
django-compressor==1.1
django-debug-toolbar==0.8.5
django-grappelli==2.3.5
django-schedule==0.5b
docutils==0.8.1
ipdb==0.6.1
ipython==0.11
pep8==0.6.1
pyflakes==0.5.0
python-dateutil==2.0
vobject==0.8.1c
wsgiref==0.1.2
```

I'm using `Python 2.7.1` on my MBP which has `10.7.2` installed.

**Comment by dugreen** [comment]
when I try to run 'python manage.py makemigrations':

 File "/home/dugeen/pyDemo/django/DjangoBlog/blog/models.py", line 8, in <module>
    from DjangoBlog.utils import cache_decorator, logger, cache
  File "/home/dugeen/pyDemo/django/DjangoBlog/DjangoBlog/utils.py", line 24, in <module>
    import _thread
ImportError: No module named _thread
